extends Area3D


func _on_body_entered(body: Node3D) -> void:
	($/root/Level/TrapShoot1 as test_enemy).spawn()
	($/root/Level/TrapShoot2 as test_enemy).spawn()
	($/root/Level/TrapShoot3 as test_enemy).spawn()
	($/root/Level/TrapShoot4 as test_enemy).spawn()
	($/root/Level/TrapShoot5 as test_enemy).spawn()
	($/root/Level/TrapShoot6 as test_enemy).spawn()
	($/root/Level/TrapShoot7 as test_enemy).spawn()
	($/root/Level/TrapShoot8 as test_enemy).spawn()
	($/root/Level/TrapThrow1 as test_enemy).spawn()
	($/root/Level/TrapThrow2 as test_enemy).spawn()
	($/root/Level/TrapThrow3 as test_enemy).spawn()
	($/root/Level/TrapThrow4 as test_enemy).spawn()
	($/root/Level/TrapThrow5 as test_enemy).spawn()
	($/root/Level/TrapThrow6 as test_enemy).spawn()
	($/root/Level/TrapThrow7 as test_enemy).spawn()
	($/root/Level/TrapPursuit1 as test_enemy).spawn()
	($/root/Level/TrapPursuit2 as test_enemy).spawn()
	($/root/Level/TrapPursuit3 as test_enemy).spawn()
	($/root/Level/TrapPursuit4 as test_enemy).spawn()
	($/root/Level/TrapPursuit5 as test_enemy).spawn()
	($/root/Level/TrapPursuit6 as test_enemy).spawn()
	($/root/Level/TrapPursuit7 as test_enemy).spawn()
	($/root/Level/TrapPursuit8 as test_enemy).spawn()
	($/root/Level/TrapPursuit9 as test_enemy).spawn()
	($/root/Level/TrapChase1 as test_enemy).spawn()
	($/root/Level/TrapChase2 as test_enemy).spawn()
	($/root/Level/TrapChase3 as test_enemy).spawn()
	($/root/Level/TrapChase4 as test_enemy).spawn()
	($/root/Level/TrapChase5 as test_enemy).spawn()
	($/root/Level/TrapChase6 as test_enemy).spawn()
	($/root/Level/TrapChase7 as test_enemy).spawn()
	($/root/Level/TrapChase8 as test_enemy).spawn()
	($/root/Level/TrapChase9 as test_enemy).spawn()
	($/root/Level/TrapChase10 as test_enemy).spawn()
	($/root/Level/TrapChase11 as test_enemy).spawn()
	($/root/Level/TrapChase12 as test_enemy).spawn()
	queue_free()
